import type { Metadata } from "next"
import localFont from "next/font/local"
import type { PropsWithChildren } from "react"
import { Footer } from "~/components/footer"
import { Header } from "~/components/header"
import { Container } from "~/components/ui/container"
import { GradientBlur } from "~/components/ui/gradient-blur"
import { Stars } from "~/components/ui/stars"
import { Toaster } from "~/components/ui/toaster"
import { cx } from "~/utils/cva"

import "./styles.css"
import { TooltipProvider } from "@radix-ui/react-tooltip"
import { Newsletter } from "~/components/newsletter"

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
})

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <body
        className={cx(
          `${geistSans.variable} ${geistMono.variable} min-h-dvh flex flex-col bg-background text-foreground font-sans`,
        )}
      >
        <TooltipProvider delayDuration={0} disableHoverableContent>
          <Header />

          <Container className="flex-1 flex flex-col gap-12 py-12 mt-[calc(var(--header-top)+var(--header-height))] md:pt-16 md:gap-16 lg:pt-20 lg:gap-20">
            {true && <GradientBlur position="top" />}

            <Stars className="fixed left-1/2 -top-0 -z-10 w-full min-w-[1000px] max-w-screen-2xl aspect-[10/5] mx-auto scale-y-flip -translate-x-1/2 -translate-y-1/3" />

            {children}

            {true && (
              <Newsletter
                title="Subscribe to our newsletter"
                description="Stay updated with the newest additions to our digital assets library, upcoming promotions or discounts."
                className="mt-auto"
              />
            )}

            {true && <GradientBlur position="bottom" />}
          </Container>

          <Footer />

          <Toaster />
        </TooltipProvider>
      </body>
    </html>
  )
}
